### DISCUSSION TITLE
Also show name of context in top part

### DISCUSSION THREAD

**Discussion by Keyruu** [Ramilito/kubectl.nvim#434] [Ideas]
I would love to see the alias of the current context in the top part of kubectl.nvim. AWS has terrible names for clusters.

**Comment by mosheavni** [comment]
how do you fetch the alias? is it part of your kubeconfig? or maybe you set a function on the env `KUBE_PS1_CLUSTER_FUNCTION`?

**Reply by Keyruu** [reply]
the alias is the name of the context. it looks like this:
```
contexts:
- context:
    cluster: arn:aws:eks:eu-central-1:XXXXXXXXX:cluster/production-shop-eks-green
    user: arn:aws:eks:eu-central-1:XXXXXXXXX:cluster/production-shop-eks-green
  name: alias-profile
```
