### ISSUE TITLE
bug: clash with mini.files

### ISSUE THREAD

**Issue by idelice** [Ramilito/kubectl.nvim#90]
### Prerequisites
* postgresql service running in k8s

### Steps to produce
1. toggle plugin on
2. navigate to services
3. press "d" (describe) on postgresql

### Actual
mini.files toggles on

### Expected
mini.files *shouldn't* pop-up

This is pretty weird, I must say. It only happens for the postgresql service i've running 😆

**Comment by Ramilito** [comment]
That's so weird, I actually had a similar problem a while back where I had to add a space to the filetype name or netrw would open!
I can't reproduce that atm though, will try to install postgress and see if that brings it back

**Comment by idelice** [comment]
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
```

**Comment by idelice** [comment]
```yaml
Name:              postgres
Namespace:         dev-ibrahim
Labels:            app.kubernetes.io/instance=postgres
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=postgres
                   app.kubernetes.io/version=1.16.0
                   helm.sh/chart=postgres-0.1.0
Annotations:       meta.helm.sh/release-name: postgres
                   meta.helm.sh/release-namespace: dev-ibrahim
Selector:          app.kubernetes.io/instance=postgres,app.kubernetes.io/name=postgres
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.109.164.134
IPs:               10.109.164.134
Port:              http  80/TCP
TargetPort:        http/TCP
Endpoints:         10.244.0.221:5432
Session Affinity:  None
Events:            <none>
```
